### ISSUE TITLE
Cannot run at all due  to errors below...

### ISSUE THREAD

**Issue by sumofat** [Breush/odin-binding-generator#14]
`
C:/work/oren/tools/bindgen/bindgen/generator-helpers.odin(52:12) 'DEFAULT_BUFFER_SIZE' is not declared by 'fmt'
C:/work/oren/tools/bindgen/bindgen/generator.odin(70:46) 'S_IRUSR' is not declared by 'os'
C:/work/oren/tools/bindgen/bindgen/generator.odin(70:59) 'S_IWUSR' is not declared by 'os'
C:/work/oren/tools/bindgen/bindgen/generator.odin(70:72) 'S_IRGRP' is not declared by 'os'
C:/work/oren/tools/bindgen/bindgen/generator.odin(70:85) 'S_IWGRP' is not declared by 'os'
C:/work/oren/tools/bindgen/bindgen/generator.odin(70:98) 'S_IROTH' is not declared by 'os'
`

Im on windows with your latest release 
and odin release 0.13

**Comment by Breush** [comment]
I do get the DEFAULT_BUFFER_SIZE issue with last odin too. Fixing it.

The others issues are due to me developing on linux and not realizing I was using linux-only feature.

**Comment by Breush** [comment]
Thanks for reporting, you can try with the last commit.
