### ISSUE TITLE
Issue with arrays within struct

### ISSUE THREAD

**Issue by WhoAteDaCake** [Breush/odin-binding-generator#22]
Hi, thanks for all your help and support with this library!

I've found another issue where

```c
struct test {
    void (*exitfuncs[32])(void);
} test;
```
Is valid code, but does not compile. As explained by https://cdecl.org/
> declare exitfuncs as array 32 of pointer to function (void) returning void

**Comment by WhoAteDaCake** [comment]
I think the binding would look like: `exitfuncs: [32](proc(rptr: rawptr) -> rawptr)`

**Comment by Breush** [comment]
Fixed, generated binding is:

```odin
issue22 :: struct {
    exitfuncs : [32]#type proc(),
};
```
(Side note, there is no `void*` in your example, so you should not expect `rawptr` types.)
