### ISSUE TITLE
Errors on bare 'short' and 'long' types

### ISSUE THREAD

**Issue by mattt-b** [Breush/odin-binding-generator#5]
When parsing types https://github.com/Breush/odin-binding-generator/blob/a146adec9709556180259fca2b4644d64f2c5142/bindgen/c-parser.odin#L102 which will parse off `short`s and `long`s as a `prefix`. It will then unconditionally eat the next token as the `main` type: https://github.com/Breush/odin-binding-generator/blob/a146adec9709556180259fca2b4644d64f2c5142/bindgen/c-parser.odin#L107
When types are just `long ident` instead of `long int ident`, this leads to things like:
```
member.type: BasicType{prefix = long , main = ident1, postfix = }
member.name: ;
[bindgen] Expected ; but got ....
```

**Comment by Breush** [comment]
Well noticed, thanks for reporting.

Will fix it as soon as I can.
