### ISSUE TITLE
Parsing error on sqlite header

### ISSUE THREAD

**Issue by zhibog** [Breush/odin-binding-generator#9]
It crashes while parsing the preprocessed header for the sqlite library.
```
[bindgen] Error: Expected identifier but found (.
[bindgen] ... from parse_type
[bindgen] ... at line 78 within this context:
```
Specifically crashes on this line
```c
void (*(*xDlSym)(sqlite3_vfs*,void*, const char *zSymbol))(void);
```
It might be the ``(*(*`` that's causing an issue.

Here is the full preprocessed header for reference: [Pastebin](https://pastebin.com/QYXiNhZD)

**Comment by Breush** [comment]
Ok, I must say that I am not even parsing this in my head.

I kind of recognize two nested function pointers, but that syntax is killing me.

Can I ask you what Odin code you would like to be generated for that?

**Comment by dotbmp** [comment]
this is a travesty of a function pointer declaration

I'm gonna look at https://fuckingfunctionpointers.com/ and get back in a min with an odinized version 🙂

**Comment by dotbmp** [comment]
I believe it would translate to this:
```odin
xDlSym: proc() -> (proc(^sqlite3_vfs, rawptr, zSymbol: cstring));
```
But I can't tell even with the link I posted, and it seems "nested function pointers", "function pointer that returns function pointer" etc are ungoogleable. Good job, C...

I don't think the problem is actually parsing the function pointer though (assuming your C parsing doesn't have a bug with recursion somewhere), but rather that the declaration is mixing named and unnamed parameters. I don't even know what to do about that; if you look at my Odin translation above, that won't compile because of `zSymbol`. Odin accepts both completely unnamed and completely named parameter lists, but this mixing is insanity.

**Comment by dotbmp** [comment]
My best guess as to what to do about this would be to detect if there is a mixture of named and unnamed parameters, and if there are, write them all out as unnamed parameters in the Odin code.

**Comment by zhibog** [comment]
I just tried to just name it in the header file and see if it changes anything.
Failed with:
```
[bindgen] Error: Expected identifier but found (.
[bindgen] ... from parse_type
[bindgen] ... at line 78 within this context:
```
So same error

**Comment by dotbmp** [comment]
I think the bindings generator assumes no recursion in function pointer types, then.

Godspeed Breush. Many intrepid programmers have been driven to madness by the dreaded function pointer syntax.

**Comment by Breush** [comment]
I analyzed the declaration, and here's what I understand.

## Why make it simple when we can make it complicated?

What I needed to understand first is that the syntax:
```c
double (*f)(int);
````
is stricly equivalent to:
```c
double f(int);
```

So the code simplifies itself to:
```c
void (*xDlSym(sqlite3_vfs*,void*, const char *zSymbol))(void);
```

## Returning a function pointer

According to the website you provided @dotbmp it now means that it's only the return value that is a function pointer of a function called `xDlSym`. So what we should generate is:
```
xDlSym: proc(unamed1: ^sqlite3_vfs, unamed2: rawptr, zSymbol: cstring) -> (proc());
```

## Now what?

Honestly, I don't want to work on parsing the "return value is function pointer" syntax.
Maybe one day, who knows. But for now, I think it's better to write that Odin part by hand and try generating the rest of it ;)
